include:
  - path:
      - ./backend/compose.yaml
services:
  web:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"