name: Backend CI (Spring Boot)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    test-and-build:
      runs-on: ubuntu-latest

      defaults:
        run:
          working-directory: ./backend
      
      env:
        SPRING_PROFILES_ACTIVE: test
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
        DB_HOST: localhost
        DB_PORT: 5432
        JWT_SECRET: much-longer-secret-with-32-characteres-for-secure
        CORS_ALLOWED_ORIGINS: "*"
      
      steps:
        - name: 1. Code checkout
          uses: actions/checkout@v4
        
        - name: 2. Java  configuration
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: 'maven'
        
        - name: 3. Give permissions to Maven Wrapper
          run: chmod +x mvnw
        
        - name: 4. Run tests and compile API
          run: ./mvnw clean verify